# Generated by Django 3.0.5 on 2020-05-05 19:14

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                always_update=True, editable=False, max_length=120, populate_from="title", unique=True
            ),
        ),
    ]
