# Generated by Django 3.0.5 on 2020-05-07 19:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("articles", "0002_auto_20200505_1914"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article", options={"default_related_name": "articles", "ordering": ["created_on"]},
        ),
        migrations.AlterField(
            model_name="article",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="articles", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
