version: '3'

services:
  db:
    image: postgres
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-healthbuddy}
      - POSTGRES_USER=${POSTGRES_USER:-ilha_healthbuddy}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-ilha102030}
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      - DEBUG=${DEBUG:-true}
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    links:
      - db
    depends_on:
      - db
