# Generated by Django 3.0.5 on 2020-05-12 13:35

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=120, unique=True)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        always_update=True, editable=False, max_length=120, populate_from="title", unique=True
                    ),
                ),
                ("subtitle", models.CharField(max_length=255)),
                ("published", models.BooleanField(default=True)),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("modified_on", models.DateTimeField(auto_now=True)),
                ("video", models.FileField(upload_to="")),
                (
                    "author",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
