# Generated by Django 3.0.5 on 2020-07-15 19:22

from django.db import migrations, models
import healthbuddy_backend.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(storage=healthbuddy_backend.storage_backends.PublicMediaStorage(), upload_to=''),
        ),
    ]
