# Generated by Django 3.0.7 on 2020-08-07 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rapidpro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flow',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='dailyflowruns',
            name='flow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='runs', to='rapidpro.Flow'),
        ),
    ]
