# Generated by Django 3.0.7 on 2020-08-10 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rapidpro', '0002_auto_20200807_1345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flow',
            old_name='active',
            new_name='is_active',
        ),
    ]
