# Generated by Django 3.0.7 on 2020-08-21 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rapidpro', '0003_auto_20200810_2207'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('uuid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DailyGroupCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('day', models.DateTimeField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='counts', to='rapidpro.Group')),
            ],
        ),
    ]
