# Generated by Django 3.0.7 on 2021-03-03 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rapidpro', '0005_channel_dailychannelcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('uuid', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DailyLabelCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=0)),
                ('day', models.DateField(auto_now=True)),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='counts', to='rapidpro.Label')),
            ],
        ),
    ]
