# Generated by Django 3.0.7 on 2021-03-09 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rapidpro', '0006_dailylabelcount_label'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_msg_rp', models.IntegerField(unique=True, verbose_name='Rapidpro message ID')),
                ('day', models.DateTimeField()),
                ('labels', models.ManyToManyField(related_name='messages', to='rapidpro.Label')),
            ],
        ),
        migrations.DeleteModel(
            name='DailyLabelCount',
        ),
    ]
